name: Terraform CI/CD

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Initialize Terraform
      run: |
        cd terraform  # Navigate to the terraform directory
        terraform init

    - name: Terraform Plan
      run: |
        cd terraform  # Navigate to the terraform directory
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          terraform plan -input=false -var-file=prod.tfvars -out=tfplan
        else
          terraform plan -input=false -var-file=exp.tfvars -out=tfplan
        fi

  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' # Only apply for main branch
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Initialize Terraform
      run: |
        cd terraform  # Navigate to the terraform directory
        terraform init

    - name: Terraform Apply (Manual Approval)
      run: |
        cd terraform  # Navigate to the terraform directory
        terraform apply -auto-approve tfplan
